sudo: required
language: node_js
node_js:
- node
services:
- docker
env:
  matrix:
  - DISABLE_SANDBOX=true
  global:
    secure: mFpNNNH0/CHFKhTWX2E056SFY0IqmNq33C5RYokBz/k4xQrp6QrGv2Te24XtO2YpxwTR4P04ficpVNF4DKMLNWm1qB/x5YDqJyfS9sNQCqpvcaS6UDRV6C1GcX53HBroY47F2+y50Pv1pc9jpfWCFBLTIVroA1itx01uGIUSQaiI39/8TXHEsZ9S+xUo47XdQ156skwHwS0Qv1mhp70urLoJAndjCp2ozYHm5bcl/vIEZ+CYmgpJAQcUQNi5HX3TgN+E56nI7nPMmXvfv+9rIBcSImphOOVpBgPFo4GeS2kly2GZLFcXvFwCnToGVBfCZQTWiqnT7sGSyezkklhzAAk0S+vBzZJVJ0YdcwLnl3Kq9QoyM8zHsLJo6d4srWrNUHVOfKHSSq0XFwVrpd7erzLRBO4asgUnzxApVpqEwOKwGbyoq6GmilUvr2MIyCaiSVqT83P1Gvkrq3SVA4JyF921Wx7N3VOikNtJSC2FnGvVhhL1c6XwshzPCz1W//nH7+OGh+e6RVzazhpjClWFlnkz6RYzbgx0vzKzZE0nPaco9Ol01ECd25/cRnJaYB+IJ7j3RDF1KiPnASSg1LsqZovvPLU4qnlWjYWkejasP7Ajm8ON7a/acFX/XlwVSXk3Hg6cBPXD82M2EydIasApO2QdRawvwhtP9Kz0w4a1DOE=
